const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

const cartConstant = { ADD_TO_CART, REMOVE_CART_ITEM, SAVE_SHIPPING_INFO };

export default cartConstant;
