const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

const CLEAR_ERRORS = "CLEAR_ERRORS";

const orderConstants = {
  CREATE_ORDER_REQUEST,
  CREATE_ORDER_SUCCESS,
  CREATE_ORDER_FAIL,
  MY_ORDERS_REQUEST,
  MY_ORDERS_SUCCESS,
  MY_ORDERS_FAIL,
  CLEAR_ERRORS,
};

export default orderConstants;
