const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

// Admin Order
const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";

const UPDATE_ORDERS_REQUEST = "UPDATE_ORDERS_REQUEST";
const UPDATE_ORDERS_SUCCESS = "UPDATE_ORDERS_SUCCESS";
const UPDATE_ORDERS_FAIL = "UPDATE_ORDERS_FAIL";
const UPDATE_ORDERS_RESET = "UPDATE_ORDERS_RESET";

const DELETE_ORDERS_REQUEST = "DELETE_ORDERS_REQUEST";
const DELETE_ORDERS_SUCCESS = "DELETE_ORDERS_SUCCESS";
const DELETE_ORDERS_FAIL = "DELETE_ORDERS_FAIL";
const DELETE_ORDERS_RESET = "DELETE_ORDERS_RESET";

const CLEAR_ERRORS = "CLEAR_ERRORS";

const orderConstants = {
  CREATE_ORDER_REQUEST,
  CREATE_ORDER_SUCCESS,
  CREATE_ORDER_FAIL,
  MY_ORDERS_REQUEST,
  MY_ORDERS_SUCCESS,
  MY_ORDERS_FAIL,

  ORDER_DETAILS_REQUEST,
  ORDER_DETAILS_SUCCESS,
  ORDER_DETAILS_FAIL,

  ALL_ORDERS_REQUEST,
  ALL_ORDERS_SUCCESS,
  ALL_ORDERS_FAIL,

  UPDATE_ORDERS_REQUEST,
  UPDATE_ORDERS_SUCCESS,
  UPDATE_ORDERS_FAIL,
  UPDATE_ORDERS_RESET,

  DELETE_ORDERS_REQUEST,
  DELETE_ORDERS_SUCCESS,
  DELETE_ORDERS_FAIL,
  DELETE_ORDERS_RESET,

  CLEAR_ERRORS,
};

export default orderConstants;
