const ALL_PRODUCT_REQUESTS = "ALL_PRODUCT_REQUESTS";
const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

const ADMIN_PRODUCT_REQUESTS = "ADMIN_PRODUCT_REQUESTS";
const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

const NEW_PRODUCT_REQUESTS = "NEW_PRODUCT_REQUESTS";
const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

const DELETE_PRODUCT_REQUESTS = "DELETE_PRODUCT_REQUESTS";
const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

const PRODUCT_DETAILS_REQUESTS = "PRODUCT_DETAILS_REQUESTS";
const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

const CLEAR_ERRORS = "CLEAR_ERRORS";

const productConstants = {
  ADMIN_PRODUCT_REQUESTS,
  ADMIN_PRODUCT_SUCCESS,
  ADMIN_PRODUCT_FAIL,
  ALL_PRODUCT_REQUESTS,
  ALL_PRODUCT_SUCCESS,
  ALL_PRODUCT_FAIL,
  NEW_PRODUCT_REQUESTS,
  NEW_PRODUCT_SUCCESS,
  NEW_PRODUCT_RESET,
  NEW_PRODUCT_FAIL,
  PRODUCT_DETAILS_REQUESTS,
  PRODUCT_DETAILS_SUCCESS,
  PRODUCT_DETAILS_FAIL,
  DELETE_PRODUCT_REQUESTS,
  DELETE_PRODUCT_SUCCESS,
  DELETE_PRODUCT_RESET,
  DELETE_PRODUCT_FAIL,
  CLEAR_ERRORS,
};

export default productConstants;
