const ALL_PRODUCT_REQUESTS = "ALL_PRODUCT_REQUESTS";
const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

const PRODUCT_DETAILS_REQUESTS = "PRODUCT_DETAILS_REQUESTS";
const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

const CLEAR_ERRORS = "CLEAR_ERRORS";

const productConstants = {
  ALL_PRODUCT_REQUESTS,
  ALL_PRODUCT_SUCCESS,
  ALL_PRODUCT_FAIL,
  PRODUCT_DETAILS_REQUESTS,
  PRODUCT_DETAILS_SUCCESS,
  PRODUCT_DETAILS_FAIL,
  CLEAR_ERRORS,
};

export default productConstants;
