const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

const CLEAR_ERRORS = "CLEAR_ERRORS";

const reviewConstants = {
  NEW_REVIEW_REQUEST,
  NEW_REVIEW_SUCCESS,
  NEW_REVIEW_RESET,
  NEW_REVIEW_FAIL,
  ALL_REVIEW_REQUEST,
  ALL_REVIEW_SUCCESS,
  ALL_REVIEW_FAIL,
  DELETE_REVIEW_REQUEST,
  DELETE_REVIEW_SUCCESS,
  DELETE_REVIEW_RESET,
  DELETE_REVIEW_FAIL,
  CLEAR_ERRORS,
};

export default reviewConstants;
